# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('parallel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'verbose_name': 'Group',
                'db_table': 'manager_group',
            },
        ),
        migrations.CreateModel(
            name='GroupBuildPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
                'verbose_name_plural': 'Group pipeline',
                'verbose_name': 'Group pipeline',
                'db_table': 'manager_group_build_pipeline',
            },
        ),
        migrations.AlterModelTable(
            name='actionhistory',
            table='manager_servers_action_history',
        ),
        migrations.AlterModelTable(
            name='buildpipeline',
            table='manager_build_pipeline',
        ),
        migrations.AlterModelTable(
            name='buildtarget',
            table='manager_build_targets',
        ),
        migrations.AlterModelTable(
            name='client',
            table='manager_clients',
        ),
        migrations.AlterModelTable(
            name='playbook',
            table='manager_playbooks',
        ),
        migrations.AlterModelTable(
            name='project',
            table='manager_projects',
        ),
        migrations.AlterModelTable(
            name='server',
            table='manager_servers',
        ),
        migrations.AddField(
            model_name='groupbuildpipeline',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.BuildTarget'),
        ),
        migrations.AddField(
            model_name='groupbuildpipeline',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.BuildGroup'),
        ),
        migrations.AddField(
            model_name='buildgroup',
            name='builds',
            field=models.ManyToManyField(through='task_manager.GroupBuildPipeline', to='task_manager.BuildTarget'),
        ),
        migrations.AddField(
            model_name='buildgroup',
            name='trigger_on_fail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fail_trigger', to='task_manager.BuildGroup'),
        ),
        migrations.AddField(
            model_name='buildgroup',
            name='trigger_on_success',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_trigger', to='task_manager.BuildGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='groupbuildpipeline',
            unique_together=set([('group', 'build')]),
        ),
    ]
