# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 13:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manager_servers_action_history',
                'verbose_name': 'Action history',
                'verbose_name_plural': 'Action history',
            },
        ),
        migrations.CreateModel(
            name='BuildPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('order',),
                'db_table': 'manager_build_pipeline',
                'verbose_name': 'Server pipeline',
                'verbose_name_plural': 'Server pipeline',
            },
        ),
        migrations.CreateModel(
            name='BuildTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'manager_build_targets',
                'verbose_name': 'Build Target',
                'verbose_name_plural': 'Build Targets',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('contacts', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'manager_clients',
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('playbook', models.TextField()),
                ('local', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'manager_playbooks',
                'verbose_name': 'Playbook',
                'verbose_name_plural': 'Playbooks',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Client')),
            ],
            options={
                'db_table': 'manager_projects',
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('ssh_port', models.IntegerField(default=22)),
                ('domain', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('ip_v4', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('ip_v6', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('private_key', models.TextField(blank=True, default=None, null=True)),
                ('public_key', models.TextField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'manager_servers',
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.AddField(
            model_name='buildtarget',
            name='pipeline',
            field=models.ManyToManyField(through='manager.BuildPipeline', to='manager.Playbook'),
        ),
        migrations.AddField(
            model_name='buildtarget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Project'),
        ),
        migrations.AddField(
            model_name='buildtarget',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Server'),
        ),
        migrations.AddField(
            model_name='buildpipeline',
            name='build_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.BuildTarget'),
        ),
        migrations.AddField(
            model_name='buildpipeline',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Playbook'),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Playbook'),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Server'),
        ),
        migrations.AlterUniqueTogether(
            name='buildpipeline',
            unique_together=set([('playbook', 'build_target')]),
        ),
    ]
